/*
視聴可能チャンネル一覧ビュー。チャンネルID、物理チャンネル番号、放送局名を表示する。除外設定されたチャンネルは表示しない。
 */
CREATE SQL SECURITY INVOKER VIEW USEABLECHANNEL AS SELECT `CHANNEL_ID` , `CHANNEL_NO` , `DISPLAY_NAME` FROM CHANNEL 
WHERE NOT EXISTS (SELECT * FROM EXCLUDECHANNEL WHERE EXCLUDECHANNEL.CHANNEL_ID=CHANNEL.CHANNEL_ID);

